-- Миграция 32 объектов из crm-data.json в PostgreSQL
-- Запускать в Render → PostgreSQL → Query Console
-- или через psql: psql "$DATABASE_URL" -f crm-seed.sql

INSERT INTO objects (id, type, category, title, description, address, "areaTotal", price, status, featured, "createdAt", "updatedAt") VALUES

-- Жилая недвижимость (rows 0-9)
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Riverdale', 'Riverdale | Аренда, Продажа', '2-й Павелецкий проезд, д. 5, стр. 1', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'ЖК "Пресня сити"', 'ЖК "Пресня сити" | Продажа', 'Москва, Ходынская ул., д.2', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'ЖК "Царская площадь"', 'ЖК "Царская площадь" | Продажа', 'Москва, Ленинградский проспект, д. 31', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Загородный дом 508 кв.м. во Владивостоке', 'Загородный дом 508 кв.м. во Владивостоке | Продажа', 'Владивосток, ул. Находкинская д. 11 г', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа 3-х комнатной квартиры 81 кв.м. в Строгино', 'Продажа 3-х комнатной квартиры 81 кв.м. в Строгино | Продажа', 'Москва, улица Твардовского, 12к1', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа загородного дома 344 кв.м. в Новомосковском районе г. Москва', 'Продажа загородного дома 344 кв.м. в Новомосковском районе г. Москва | Продажа', 'Москва, поселение Щаповское, квартал № 39', 0, 35000000, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", '3-х комнатная квартира в Хамовниках 121,3 кв.м.', '3-х комнатная квартира в Хамовниках 121,3 кв.м. | Продажа', 'Москва, улица Усачёва, 15кБ', 0, 160000000, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Квартира студио 17 кв.м.', 'Квартира студио 17 кв.м. | Продажа', 'Москва, Зеленоград, к814', 0, 5000000, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа здания 783 кв.м. Садовая - Спасская д. 19 стр. 3', 'Продажа здания 783 кв.м. Садовая - Спасская д. 19 стр. 3 | Продажа', 'Садовая - Спасская д. 19 стр. 3', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа гостиницы 3*', 'Продажа гостиницы 3* | Продажа', 'Москва, Серебрянический переулок, 12с1', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),

-- Инвестиционные предложения (rows 10-27)
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа здания 1 216 кв.м. в г. Пересвет', 'Продажа здания 1 216 кв.м. в г. Пересвет', 'Московская область, Сергиево-Посадский городской округ, Пересвет, Советская улица, 3', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа комплекса зданий общей площадью 18 338 кв.м. на земельном участке 2,38 га.', 'Продажа комплекса зданий общей площадью 18 338 кв.м. на земельном участке 2,38 га.', 'Москва, Сельскохозяйственная улица, 17к2', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа комплекса зданий общей площадью 13 800 кв.м. на земельном участке 1,94 га.', 'Продажа комплекса зданий общей площадью 13 800 кв.м. на земельном участке 1,94 га.', 'Москва, Сельскохозяйственная улица, 17к2', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа участка 0,8 га под строительство комплекса апартаментов', 'Продажа участка 0,8 га под строительство комплекса апартаментов | Продажа', 'Москва, Сетунь', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'OFFICE'::"ObjectCategory", 'Административный комплекс 1 100 кв.м. на зу 0,5 га', 'Административный комплекс 1 100 кв.м. на зу 0,5 га', 'Москва, Варшавское шоссе, 66к2', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Участок под жилую застройку 0,21 га', 'Участок под жилую застройку 0,21 га | Продажа', 'Москва, Мерзляковский переулок, 22', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'RETAIL'::"ObjectCategory", 'Продажа автосалона 4 275 кв.м. на з/у 0,94 га', 'Продажа автосалона 4 275 кв.м. на з/у 0,94 га', 'Москва, улица Обручева, 54', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа здания 10 000 кв.м. Милютинский пер-к, д. 5 стр.1', 'Продажа здания 10 000 кв.м. Милютинский пер-к, д. 5 стр.1 | Строительство под заказчика', 'Москва, Милютинский пер-к, д.5 стр.1', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'RETAIL'::"ObjectCategory", 'Продажа помещения под автомойку в ЖК "Headliner"', 'Продажа помещения под автомойку в ЖК "Headliner" | Продажа', 'Москва, Центральный административный округ, Пресненский район, жилой комплекс Хедлайнер', 0, 130000, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'RETAIL'::"ObjectCategory", 'Продажа помещения под автомойку в действующем ЖК "I Love"', 'Продажа помещения под автомойку в действующем ЖК "I Love" | Продажа', 'Москва, Звёздный бульвар, 21с1', 0, 48000000, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'OFFICE'::"ObjectCategory", 'Продажа административного здания под редевелопмент', 'Продажа административного здания под редевелопмент | Продажа', 'Москва, улица Академика Капицы, 32А', 0, 360000000, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа пансионата в Крыму 40 км от Симферополя', 'Продажа пансионата в Крыму 40 км от Симферополя | Продажа', 'Крым, пос. Утес', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа кинотеатра "Восход" под реконструкцию', 'Продажа кинотеатра "Восход" под реконструкцию | Продажа', 'Москва, Михайлова, д. 29', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа земельного участка 1,2 га под строительство ТЦ или жилого дома', 'Продажа земельного участка 1,2 га под строительство ТЦ или жилого дома | Продажа', 'Москва, Дмитровское ш. 49', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа участка 0,93 га под строительство жилого комплекса', 'Продажа участка 0,93 га под строительство жилого комплекса | Продажа', 'Москва, Саймоновский пер., вл. 3', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'RETAIL'::"ObjectCategory", 'Продажа готового бизнеса - магазин "Пятерочка" г. Пушкино МО', 'Продажа готового бизнеса - магазин "Пятерочка" г. Пушкино МО | Продажа', 'Московская область, Пушкинский район, поселок городского типа Правдинский, Советская улица, уч.3б', 0, 75000000, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'RETAIL'::"ObjectCategory", 'Продажа готового бизнеса - магазин "Дикси" Сергиев - Посад', 'Продажа готового бизнеса - магазин "Дикси" Сергиев - Посад | Продажа', 'Сергиево-Посадский муниципальный район, городское поселение Богородское, рабочий поселок Богородское, д.27/1', 0, 60000000, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'PRODUCTION'::"ObjectCategory", 'Продажа производственного комплекса 16 770 кв.м. на з/у 1,37 га', 'Продажа производственного комплекса 16 770 кв.м. на з/у 1,37 га', 'Москва, 4-й Рощинский проезд, 20с1', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),

-- Земельные участки (rows 28-31)
(gen_random_uuid(), 'SALE'::"ObjectType", 'PRODUCTION'::"ObjectCategory", 'Участки промышленного назначения в г. Воронеж', 'Участки промышленного назначения в г. Воронеж | Продажа', 'Воронеж', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Участок под жилую застройку 0,3 га', 'Участок под жилую застройку 0, 3 га | Продажа', 'Москва, переулок Обуха, 3', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа з/у под жилую застройку 0,68 га', 'Продажа з/у под жилую застройку 0,68 га | Продажа', 'Москва, 1-й Котляковский переулок, 4А', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW()),
(gen_random_uuid(), 'SALE'::"ObjectType", 'FREE_PURPOSE'::"ObjectCategory", 'Продажа з/у под жилую застройку 1,37 га', 'Продажа з/у под жилую застройку 1,37 га | Продажа', 'Москва, Сельскохозяйственная улица, 42с1', 0, 0, 'ACTIVE'::"ObjectStatus", false, NOW(), NOW());
